(require 'json)

(let ((location "prepare") (message "entry") (hypothesis-id "F")
      (data (list (cons :buffer "note.org"))))
  (condition-case err
      (let* ((payload (list (cons "sessionId" "c9fe51")
                            (cons "hypothesisId" hypothesis-id)
                            (cons "location" location)
                            (cons "message" message)
                            (cons "data" (let ((print-length nil) (print-level nil))
                                           (mapcar (lambda (kv)
                                                     (cons (if (keywordp (car kv))
                                                               (symbol-name (car kv))
                                                             (car kv))
                                                           (cadr kv)))
                                                   data)))
                            (cons "timestamp" (floor (* 1000 (float-time))))))
             (line (concat (json-encode payload) "\n")))
        (message "line=%S" line)
        (append-to-file line nil "/Users/fangyu/.emacs.d/.cursor/debug-c9fe51.log")
        :ok)
    (error (message "ERR: %s" (error-message-string err)))))
