(load "/Users/fangyu/.emacs.d/custom/setup-inline-crypt.el" nil t t)

(with-current-buffer (generate-new-buffer "*e2e-flow*")
  (setq buffer-file-name "/tmp/e2e-inline-note.org")
  (org-mode)
  (inline-crypt-mode 1)
  (insert "* sec :crypt:\n\nmy secret line one\nmy secret line two\n\n* normal\n")
  (goto-char (point-min))
  (search-forward "my secret line one")
  (let ((beg (point))
        (end (progn (goto-char (point-max)) (search-backward "line two") (line-end-position))))
    (goto-char beg)
    (push-mark end nil t)
    (activate-mark)
    (inline-crypt-encrypt-region beg end))
  (message "E2E after encrypt: block=%S collapsed=%S"
           (inline-crypt--find-block-bounds)
           (inline-crypt--collapsed-at-point))
  (goto-char (point-min))
  (search-forward "🔐" nil t)
  (inline-crypt-decrypt-at-point)
  (message "E2E after decrypt: registry=%S props=%S"
           (length inline-crypt--decrypted-blocks)
           (inline-crypt--decrypted-at-point))
  (let ((reg (inline-crypt--decrypted-at-point)))
    (goto-char (car reg))
    (insert "EDITED "))
  (setq buffer-modified-p t)
  (condition-case err
      (progn
        (setq-local before-save-hook '(inline-crypt--reencrypt-before-save))
        (basic-save-buffer)
        (message "E2E save OK"))
    (error (message "E2E save ERR: %s" (error-message-string err))))
  (message "E2E final pgp-count=%S has-delimiter=%S file-size=%S"
           (save-excursion (goto-char (point-min))
             (let ((n 0)) (while (re-search-forward "-----BEGIN PGP MESSAGE-----" nil t) (setq n (1+ n))) n))
           (save-excursion (goto-char (point-min)) (re-search-forward "#+BEGIN_gpg" nil t))
           (when (file-exists-p buffer-file-name)
             (nth 5 (file-attributes buffer-file-name)))))
